// ZTSC console shim — backend `console` (not from DOM).
// Generated by src/lib/gen_lib.js — do not edit by hand.
//
// `console` lives in lib.dom, not the ES chain. Loaded ONLY when esnext is
// selected without dom (lib:["esnext"]); DOM configs use lib.dom's richer
// `Console` instead, so this shim is not loaded then (no duplicate var).

declare var console: {
    log(...data: any[]): void;
    error(...data: any[]): void;
    warn(...data: any[]): void;
    info(...data: any[]): void;
    debug(...data: any[]): void;
};
