#!/usr/bin/env node
// Generates deterministic synthetic TypeScript corpora for benchmarking.
//
// Output: bench/corpus/small (~5k LOC) and bench/corpus/medium (~50k LOC).
// The generated code stays inside the ztsc v0.0.1 subset (PLAN.md §5):
// interfaces, type aliases, unions, classes, functions, narrowing.
//
// Usage: node bench/gen_corpus.js [--force]

"use strict";

const fs = require("fs");
const path = require("path");

// One generated module is ~110 lines (lib-free: the ztsc checker has no
// lib.d.ts, so the corpus avoids globals and primitive/array methods).
const SIZES = {
  small: { files: 10, modulesPerFile: 5 }, // ~5k LOC
  medium: { files: 50, modulesPerFile: 9 }, // ~50k LOC
};

// Deterministic PRNG (LCG) so corpora are reproducible.
function makeRng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}

function genModule(fileIdx, modIdx, rng) {
  const id = `F${fileIdx}M${modIdx}`;
  const kinds = ['"circle"', '"square"'];
  const kind = kinds[Math.floor(rng() * kinds.length)];
  const n = Math.floor(rng() * 100);
  return `// module ${id}
export interface Point${id} {
  x: number;
  y: number;
  label?: string;
}

export interface Circle${id} {
  kind: "circle";
  center: Point${id};
  radius: number;
}

export interface Square${id} {
  kind: "square";
  origin: Point${id};
  side: number;
}

export type Shape${id} = Circle${id} | Square${id};

export type Result${id} = { ok: true; value: number } | { ok: false; error: string };

export function area${id}(shape: Shape${id}): number {
  if (shape.kind === "circle") {
    return 3.14159 * shape.radius * shape.radius;
  }
  return shape.side * shape.side;
}

export function describe${id}(shape: Shape${id}, verbose?: boolean): string {
  const a = area${id}(shape);
  if (verbose && a > ${n}) {
    return shape.kind + "!";
  }
  return shape.kind;
}

export function tryDivide${id}(a: number, b: number): Result${id} {
  if (b === 0) {
    return { ok: false, error: "division by zero" };
  }
  return { ok: true, value: a / b };
}

export function unwrap${id}(r: Result${id}, fallback: number): number {
  if (r.ok) {
    return r.value;
  }
  return r.error.length === 0 ? fallback : 0 - fallback;
}

export class Registry${id}<T> {
  items: T[] = [];
  size: number = 0;

  add(item: T): number {
    this.items[this.size] = item;
    this.size = this.size + 1;
    return this.size;
  }

  get(index: number): T | undefined {
    return index < this.size ? this.items[index] : undefined;
  }

  count(): number {
    return this.size;
  }
}

export function process${id}(input: string | number | null): string {
  if (input === null) {
    return "null";
  }
  if (typeof input === "number") {
    return "n:" + input;
  }
  return input;
}

export function firstLabel${id}(points: Point${id}[]): string {
  for (const p of points) {
    if (p.label) {
      return p.label;
    }
  }
  return "none";
}

export function fmt${id}(x: string): string;
export function fmt${id}(x: number): string;
export function fmt${id}(x: string | number): string {
  if (typeof x === "string") {
    return x;
  }
  return "#" + x;
}

export function ident${id}<T>(x: T): T {
  return x;
}

const registry${id} = new Registry${id}<Shape${id}>();
registry${id}.add({ kind: ${kind}, ${
    kind === '"square"' ? "origin: { x: 0, y: 0 }, side: 2" : "center: { x: 0, y: 0 }, radius: 1"
  } });
export const count${id}: number = registry${id}.count();
export const desc${id}: string = describe${id}({ kind: "circle", center: { x: 1, y: 1 }, radius: 2 }, true);
export const num${id}: number = ident${id}(${n});
export const label${id}: string = fmt${id}(count${id});
`;
}

function genFile(fileIdx, modulesPerFile, rng) {
  let out = `// Generated by bench/gen_corpus.js — do not edit.\n\n`;
  for (let m = 0; m < modulesPerFile; m++) {
    out += genModule(fileIdx, m, rng) + "\n";
  }
  return out;
}

function main() {
  const force = process.argv.includes("--force");
  const root = path.join(__dirname, "corpus");
  let totalLoc = 0;
  for (const [name, cfg] of Object.entries(SIZES)) {
    const dir = path.join(root, name);
    if (fs.existsSync(dir) && !force) {
      console.log(`corpus '${name}' already exists at ${dir} (use --force to regenerate)`);
      continue;
    }
    fs.mkdirSync(dir, { recursive: true });
    const rng = makeRng(0xc0ffee + Object.keys(SIZES).indexOf(name));
    let loc = 0;
    for (let f = 0; f < cfg.files; f++) {
      const content = genFile(f, cfg.modulesPerFile, rng);
      fs.writeFileSync(path.join(dir, `file_${String(f).padStart(3, "0")}.ts`), content);
      loc += content.split("\n").length;
    }
    // Minimal tsconfig so `tsc`/`tsgo` can check the corpus for comparison runs.
    fs.writeFileSync(
      path.join(dir, "tsconfig.json"),
      JSON.stringify(
        {
          compilerOptions: {
            strict: true,
            noEmit: true,
            target: "es2020",
            module: "es2020",
            lib: ["es2020"],
          },
          include: ["*.ts"],
        },
        null,
        2,
      ) + "\n",
    );
    console.log(`generated corpus '${name}': ${cfg.files} files, ~${loc} LOC in ${dir}`);
    totalLoc += loc;
  }
  if (totalLoc > 0) console.log(`total: ~${totalLoc} LOC`);
}

main();
