#!/usr/bin/env node
// Generates deterministic synthetic TypeScript corpora for benchmarking.
//
// Output: bench/corpus/small (~5k LOC) and bench/corpus/medium (~50k LOC).
// The generated code stays inside the ztsc v0.0.1 subset (PLAN.md §5):
// interfaces, type aliases, unions, classes, functions, narrowing.
//
// Usage: node bench/gen_corpus.js [--force]

"use strict";

const fs = require("fs");
const path = require("path");

// One generated module is ~76 lines.
const SIZES = {
  small: { files: 10, modulesPerFile: 7 }, // ~5k LOC
  medium: { files: 50, modulesPerFile: 13 }, // ~50k LOC
};

// Deterministic PRNG (LCG) so corpora are reproducible.
function makeRng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}

function genModule(fileIdx, modIdx, rng) {
  const id = `F${fileIdx}M${modIdx}`;
  const kinds = ['"circle"', '"square"', '"triangle"'];
  const kind = kinds[Math.floor(rng() * kinds.length)];
  const n = Math.floor(rng() * 100);
  return `// module ${id}
export interface Point${id} {
  x: number;
  y: number;
  label?: string;
}

export interface Circle${id} {
  kind: "circle";
  center: Point${id};
  radius: number;
}

export interface Square${id} {
  kind: "square";
  origin: Point${id};
  side: number;
}

export type Shape${id} = Circle${id} | Square${id};

export type Result${id} = { ok: true; value: number } | { ok: false; error: string };

export function area${id}(shape: Shape${id}): number {
  if (shape.kind === "circle") {
    return Math.PI * shape.radius * shape.radius;
  }
  return shape.side * shape.side;
}

export function describe${id}(shape: Shape${id}, verbose?: boolean): string {
  const a = area${id}(shape);
  if (verbose) {
    return shape.kind + " with area " + a.toFixed(2);
  }
  return shape.kind;
}

export function tryDivide${id}(a: number, b: number): Result${id} {
  if (b === 0) {
    return { ok: false, error: "division by zero" };
  }
  return { ok: true, value: a / b };
}

export class Registry${id}<T> {
  private items: T[] = [];

  add(item: T): number {
    this.items.push(item);
    return this.items.length;
  }

  get(index: number): T | undefined {
    return this.items[index];
  }

  count(): number {
    return this.items.length;
  }
}

export function process${id}(input: string | number | null): string {
  if (input === null) {
    return "null";
  }
  if (typeof input === "number") {
    return input.toFixed(${n % 5});
  }
  return input.trim();
}

const registry${id} = new Registry${id}<Shape${id}>();
registry${id}.add({ kind: ${kind === '"triangle"' ? '"circle"' : kind}, ${
    kind === '"square"' ? 'origin: { x: 0, y: 0 }, side: 2' : "center: { x: 0, y: 0 }, radius: 1"
  } } as Shape${id});
export const count${id}: number = registry${id}.count();
`;
}

function genFile(fileIdx, modulesPerFile, rng) {
  let out = `// Generated by bench/gen_corpus.js — do not edit.\n\n`;
  for (let m = 0; m < modulesPerFile; m++) {
    out += genModule(fileIdx, m, rng) + "\n";
  }
  return out;
}

function main() {
  const force = process.argv.includes("--force");
  const root = path.join(__dirname, "corpus");
  let totalLoc = 0;
  for (const [name, cfg] of Object.entries(SIZES)) {
    const dir = path.join(root, name);
    if (fs.existsSync(dir) && !force) {
      console.log(`corpus '${name}' already exists at ${dir} (use --force to regenerate)`);
      continue;
    }
    fs.mkdirSync(dir, { recursive: true });
    const rng = makeRng(0xc0ffee + Object.keys(SIZES).indexOf(name));
    let loc = 0;
    for (let f = 0; f < cfg.files; f++) {
      const content = genFile(f, cfg.modulesPerFile, rng);
      fs.writeFileSync(path.join(dir, `file_${String(f).padStart(3, "0")}.ts`), content);
      loc += content.split("\n").length;
    }
    // Minimal tsconfig so `tsc`/`tsgo` can check the corpus for comparison runs.
    fs.writeFileSync(
      path.join(dir, "tsconfig.json"),
      JSON.stringify(
        {
          compilerOptions: {
            strict: true,
            noEmit: true,
            target: "es2020",
            module: "es2020",
            lib: ["es2020"],
          },
          include: ["*.ts"],
        },
        null,
        2,
      ) + "\n",
    );
    console.log(`generated corpus '${name}': ${cfg.files} files, ~${loc} LOC in ${dir}`);
    totalLoc += loc;
  }
  if (totalLoc > 0) console.log(`total: ~${totalLoc} LOC`);
}

main();
